//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACCP.Core.WP.ResourceFiles {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HACCP.Core.WP.ResourceFiles.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory Path (optional).
        /// </summary>
        public static string AddDirectoryPathoptional {
            get {
                return ResourceManager.GetString("AddDirectoryPathoptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the records will be uploaded and the checkmarks will be cleared..
        /// </summary>
        public static string Alltherecordswillbeuploadedandthecheckmarkswillbecleared {
            get {
                return ResourceManager.GetString("Alltherecordswillbeuploadedandthecheckmarkswillbecleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android requires &quot;Location&quot; permission for Bluetooth LE scanning..
        /// </summary>
        public static string AndroidrequiresLocationpermissionforBluetoothLEscanning {
            get {
                return ResourceManager.GetString("AndroidrequiresLocationpermissionforBluetoothLEscanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the records. Please try again later..
        /// </summary>
        public static string AnerroroccurredwhileuploadingtherecordsPleasetryagainlater {
            get {
                return ResourceManager.GetString("AnerroroccurredwhileuploadingtherecordsPleasetryagainlater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. We will look into it soon..
        /// </summary>
        public static string AnunexpectederrorhasoccurredWewilllookintoitsoon {
            get {
                return ResourceManager.GetString("AnunexpectederrorhasoccurredWewilllookintoitsoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the app?.
        /// </summary>
        public static string Areyousureyouwanttoexittheapp {
            get {
                return ResourceManager.GetString("Areyousureyouwanttoexittheapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string Areyousureyouwanttologout {
            get {
                return ResourceManager.GetString("Areyousureyouwanttologout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to refresh the Blue2 connection?.
        /// </summary>
        public static string AreyousureyouwanttorefreshtheBlue2connection {
            get {
                return ResourceManager.GetString("AreyousureyouwanttorefreshtheBlue2connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to switch the language of this app to {0}?.
        /// </summary>
        public static string Areyousureyouwanttoswitchthelanguageofthisappto0 {
            get {
                return ResourceManager.GetString("Areyousureyouwanttoswitchthelanguageofthisappto0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Off Interval.
        /// </summary>
        public static string AutoOffInterval {
            get {
                return ResourceManager.GetString("AutoOffInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue2.
        /// </summary>
        public static string Blue2 {
            get {
                return ResourceManager.GetString("Blue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Blue2BatteryString {
            get {
                return ResourceManager.GetString("Blue2BatteryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue2 Devices.
        /// </summary>
        public static string Blue2Devices {
            get {
                return ResourceManager.GetString("Blue2Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue2 Devices.
        /// </summary>
        public static string Blue2DevicesLabel {
            get {
                return ResourceManager.GetString("Blue2DevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Blue2HighString {
            get {
                return ResourceManager.GetString("Blue2HighString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue2 ID: .
        /// </summary>
        public static string Blue2ID {
            get {
                return ResourceManager.GetString("Blue2ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Blue2LowString {
            get {
                return ResourceManager.GetString("Blue2LowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue2 Settings.
        /// </summary>
        public static string Blue2Settings {
            get {
                return ResourceManager.GetString("Blue2Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping.
        /// </summary>
        public static string Blue2SleepString {
            get {
                return ResourceManager.GetString("Blue2SleepString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn ON the Blue2 device near you..
        /// </summary>
        public static string Blue2TurnOnMessage {
            get {
                return ResourceManager.GetString("Blue2TurnOnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        public static string Bluetooth {
            get {
                return ResourceManager.GetString("Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the Checklist as records are pending to be uploaded. To upload the records, select &quot;Upload Records&quot; under the Wireless Tasks menu..
        /// </summary>
        public static string CannotchangetheChecklistasrecordsarependingtobeuploadedTouploadtherecordsselectUploadRecordsundertheWirelessTasksmenu {
            get {
                return ResourceManager.GetString("CannotchangetheChecklistasrecordsarependingtobeuploadedTouploadtherecordsselectUp" +
                        "loadRecordsundertheWirelessTasksmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the Menu as records are pending to be uploaded. To upload the records, select &quot;Upload Records&quot; under the Wireless Tasks menu..
        /// </summary>
        public static string CannotchangetheMenuasrecordsarependingtobeuploadedTouploadtherecordsselectUploadRecordsundertheWirelessTasksmenu {
            get {
                return ResourceManager.GetString("CannotchangetheMenuasrecordsarependingtobeuploadedTouploadtherecordsselectUploadR" +
                        "ecordsundertheWirelessTasksmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot scan for Blue2 without &quot;Location&quot; permission..
        /// </summary>
        public static string CannotscanforBlue2withoutLocationpermission {
            get {
                return ResourceManager.GetString("CannotscanforBlue2withoutLocationpermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Review.
        /// </summary>
        public static string CategoryReview {
            get {
                return ResourceManager.GetString("CategoryReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string CelsciustUnit {
            get {
                return ResourceManager.GetString("CelsciustUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Records.
        /// </summary>
        public static string ChecklistRecords {
            get {
                return ResourceManager.GetString("ChecklistRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklists.
        /// </summary>
        public static string Checklists {
            get {
                return ResourceManager.GetString("Checklists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Checkmarks.
        /// </summary>
        public static string ClearCheckmarks {
            get {
                return ResourceManager.GetString("ClearCheckmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Blue2.
        /// </summary>
        public static string ConnectBlue2Label {
            get {
                return ResourceManager.GetString("ConnectBlue2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string ConnectionStatusDisconnect {
            get {
                return ResourceManager.GetString("ConnectionStatusDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for Blue2.
        /// </summary>
        public static string ConnectionStatusScanBlue2 {
            get {
                return ResourceManager.GetString("ConnectionStatusScanBlue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        public static string ConnectionStatusScanning {
            get {
                return ResourceManager.GetString("ConnectionStatusScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successful.
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout.
        /// </summary>
        public static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Action.
        /// </summary>
        public static string CorrectiveAction {
            get {
                return ResourceManager.GetString("CorrectiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Actions.
        /// </summary>
        public static string CorrectiveActions {
            get {
                return ResourceManager.GetString("CorrectiveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID: .
        /// </summary>
        public static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info.
        /// </summary>
        public static string DeviceInfoTitle {
            get {
                return ResourceManager.GetString("DeviceInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Network Connection.
        /// </summary>
        public static string EnableNetworkConnection {
            get {
                return ResourceManager.GetString("EnableNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Custom Probe Description.
        /// </summary>
        public static string EnterCustomProbeDescription {
            get {
                return ResourceManager.GetString("EnterCustomProbeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter notes about the item.
        /// </summary>
        public static string Enternotesabouttheitem {
            get {
                return ResourceManager.GetString("Enternotesabouttheitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Port (optional).
        /// </summary>
        public static string EnterPortoptional {
            get {
                return ResourceManager.GetString("EnterPortoptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Server IP Address or Domain Name..
        /// </summary>
        public static string EnterServerIPAddressorDomainName {
            get {
                return ResourceManager.GetString("EnterServerIPAddressorDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Enteryourpassword {
            get {
                return ResourceManager.GetString("Enteryourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        public static string FahrenheitUnit {
            get {
                return ResourceManager.GetString("FahrenheitUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the Blue2 device. Please try again..
        /// </summary>
        public static string FailedtoconnecttotheBlue2devicePleasetryagain {
            get {
                return ResourceManager.GetString("FailedtoconnecttotheBlue2devicePleasetryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HACCP.
        /// </summary>
        public static string HACCP {
            get {
                return ResourceManager.GetString("HACCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HACCP Manager.
        /// </summary>
        public static string HACCPManager {
            get {
                return ResourceManager.GetString("HACCPManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I moved my HACCP Enterprise application to a new server. Keep my data..
        /// </summary>
        public static string ImovedmyHACCPEnterpriseapplicationtoanewserverKeepmydata {
            get {
                return ResourceManager.GetString("ImovedmyHACCPEnterpriseapplicationtoanewserverKeepmydata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid temperature..
        /// </summary>
        public static string InvalidTemperatureAlert {
            get {
                return ResourceManager.GetString("InvalidTemperatureAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to start over with a new server. Erase all data and reset my application (resets Device ID also)..
        /// </summary>
        public static string IwanttostartoverwithanewserverErasealldataandresetmyapplicationresetsDeviceIDalso {
            get {
                return ResourceManager.GetString("IwanttostartoverwithanewserverErasealldataandresetmyapplicationresetsDeviceIDalso" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Upload.
        /// </summary>
        public static string LastUpload {
            get {
                return ResourceManager.GetString("LastUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        public static string Line1 {
            get {
                return ResourceManager.GetString("Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        public static string Line2 {
            get {
                return ResourceManager.GetString("Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection with the Blue2 device..
        /// </summary>
        public static string LostconnectionwiththeBlue2device {
            get {
                return ResourceManager.GetString("LostconnectionwiththeBlue2device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Scale.
        /// </summary>
        public static string MeasurementScale {
            get {
                return ResourceManager.GetString("MeasurementScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Timing.
        /// </summary>
        public static string MeasurementTiming {
            get {
                return ResourceManager.GetString("MeasurementTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        public static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Blue2 devices found..
        /// </summary>
        public static string NoBlue2devicesfound {
            get {
                return ResourceManager.GetString("NoBlue2devicesfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Categories Found.
        /// </summary>
        public static string NoCategoriesFound {
            get {
                return ResourceManager.GetString("NoCategoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found. Please tap &quot;Select/Change Checklist&quot; in the Wireless Tasks menu..
        /// </summary>
        public static string NocategoriesfoundPleasetapSelectChangeChecklistintheWirelessTasksMenu {
            get {
                return ResourceManager.GetString("NocategoriesfoundPleasetapSelectChangeChecklistintheWirelessTasksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Checklists Found.
        /// </summary>
        public static string NoChecklistsFound {
            get {
                return ResourceManager.GetString("NoChecklistsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No checklists found in the server..
        /// </summary>
        public static string Nochecklistsfoundintheserver {
            get {
                return ResourceManager.GetString("Nochecklistsfoundintheserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corrective actions found..
        /// </summary>
        public static string Nocorrectiveactionsfound {
            get {
                return ResourceManager.GetString("Nocorrectiveactionsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        public static string Noitemsfound {
            get {
                return ResourceManager.GetString("Noitemsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found to review..
        /// </summary>
        public static string Noitemsfoundtoreview {
            get {
                return ResourceManager.GetString("Noitemsfoundtoreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Locations Found.
        /// </summary>
        public static string NoLocationsFound {
            get {
                return ResourceManager.GetString("NoLocationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations found. Please tap &quot;Select/Change Menu&quot; in the Wireless Tasks menu..
        /// </summary>
        public static string NolocationsfoundPleasetapSelectChangeMenuintheWirelessTasksMenu {
            get {
                return ResourceManager.GetString("NolocationsfoundPleasetapSelectChangeMenuintheWirelessTasksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations match your search..
        /// </summary>
        public static string Nolocationsmatchyoursearch {
            get {
                return ResourceManager.GetString("Nolocationsmatchyoursearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Menus Found.
        /// </summary>
        public static string NoMenusFound {
            get {
                return ResourceManager.GetString("NoMenusFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No menus found in the server..
        /// </summary>
        public static string Nomenusfoundintheserver {
            get {
                return ResourceManager.GetString("Nomenusfoundintheserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions found..
        /// </summary>
        public static string Noquestionsfound {
            get {
                return ResourceManager.GetString("Noquestionsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions found to review..
        /// </summary>
        public static string Noquestionsfoundtoreview {
            get {
                return ResourceManager.GetString("Noquestionsfoundtoreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found to upload..
        /// </summary>
        public static string Norecordsfoundtoupload {
            get {
                return ResourceManager.GetString("Norecordsfoundtoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Site Information Found.
        /// </summary>
        public static string NoSiteInformationFound {
            get {
                return ResourceManager.GetString("NoSiteInformationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No site informations found. Please tap Update Site and Settings in the Wireless Tasks menu..
        /// </summary>
        public static string NositeinformationsfoundPleasetapUpdateSiteandSettingsintheWirelessTasksmenu {
            get {
                return ResourceManager.GetString("NositeinformationsfoundPleasetapUpdateSiteandSettingsintheWirelessTasksmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter NotifEYE Url.
        /// </summary>
        public static string NotifEyeUrl {
            get {
                return ResourceManager.GetString("NotifEyeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifEYE Username.
        /// </summary>
        public static string NotifEYEUserName {
            get {
                return ResourceManager.GetString("NotifEYEUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifyEYE Password.
        /// </summary>
        public static string NotifEyeUserPassword {
            get {
                return ResourceManager.GetString("NotifEyeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Manager.
        /// </summary>
        public static string NotifyManager {
            get {
                return ResourceManager.GetString("NotifyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented..
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Users Found.
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found. Please tap Update User List in the Wireless Tasks menu..
        /// </summary>
        public static string NousersfoundPleasetapUpdateUserListintheWirelessTasksmenu {
            get {
                return ResourceManager.GetString("NousersfoundPleasetapUpdateUserListintheWirelessTasksmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Web Service.
        /// </summary>
        public static string NoWebService {
            get {
                return ResourceManager.GetString("NoWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value.
        /// </summary>
        public static string Numericvalue {
            get {
                return ResourceManager.GetString("Numericvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! I still need to upload my data to the old server..
        /// </summary>
        public static string OopsIstillneedtouploadmydatatotheoldserver {
            get {
                return ResourceManager.GetString("OopsIstillneedtouploadmydatatotheoldserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect. Please try again..
        /// </summary>
        public static string PasswordincorrectPleasetryagain {
            get {
                return ResourceManager.GetString("PasswordincorrectPleasetryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some records are pending upload. Do you want to upload them to server?.
        /// </summary>
        public static string PendingCheckmarksMessage {
            get {
                return ResourceManager.GetString("PendingCheckmarksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Checklist.
        /// </summary>
        public static string PerformChecklist {
            get {
                return ResourceManager.GetString("PerformChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Probe Description.
        /// </summary>
        public static string ProbeDescriptionTitle {
            get {
                return ResourceManager.GetString("ProbeDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechill.
        /// </summary>
        public static string Rechill {
            get {
                return ResourceManager.GetString("Rechill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Answer.
        /// </summary>
        public static string RecordAnswer {
            get {
                return ResourceManager.GetString("RecordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Answer: {0} {1}Corrective Action Taken: {2}.
        /// </summary>
        public static string RecordedAnswer01CorrectiveActiontaken2 {
            get {
                return ResourceManager.GetString("RecordedAnswer01CorrectiveActiontaken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded by.
        /// </summary>
        public static string Recordedby {
            get {
                return ResourceManager.GetString("Recordedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Temperature.
        /// </summary>
        public static string RecordedTemperature {
            get {
                return ResourceManager.GetString("RecordedTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Temperature: {0}Corrective Action Taken: {1}User: {2}.
        /// </summary>
        public static string RecordedTemperature0Correctiveactiontaken1User2 {
            get {
                return ResourceManager.GetString("RecordedTemperature0Correctiveactiontaken1User2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Item.
        /// </summary>
        public static string RecordItem {
            get {
                return ResourceManager.GetString("RecordItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Item Save Preview.
        /// </summary>
        public static string RecordItemSavePreview {
            get {
                return ResourceManager.GetString("RecordItemSavePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved.
        /// </summary>
        public static string RecordSavedToast {
            get {
                return ResourceManager.GetString("RecordSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Connection.
        /// </summary>
        public static string RefreshConnection {
            get {
                return ResourceManager.GetString("RefreshConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reheat to 165F.
        /// </summary>
        public static string Reheatto165F {
            get {
                return ResourceManager.GetString("Reheatto165F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Checklist.
        /// </summary>
        public static string ReviewChecklist {
            get {
                return ResourceManager.GetString("ReviewChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Item.
        /// </summary>
        public static string ReviewItem {
            get {
                return ResourceManager.GetString("ReviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        public static string SaveandContinue {
            get {
                return ResourceManager.GetString("SaveandContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save N/A as the answer for the question?.
        /// </summary>
        public static string SavedNAastheAnswerfortheQuestion {
            get {
                return ResourceManager.GetString("SavedNAastheAnswerfortheQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save N/A as the temperature recording for the item?.
        /// </summary>
        public static string SavedNAasthetemperaturerecordingfortheitem {
            get {
                return ResourceManager.GetString("SavedNAasthetemperaturerecordingfortheitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Record.
        /// </summary>
        public static string SaveRecord {
            get {
                return ResourceManager.GetString("SaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Blue2 device....
        /// </summary>
        public static string SearchingforBlue2device {
            get {
                return ResourceManager.GetString("SearchingforBlue2device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for device....
        /// </summary>
        public static string Searchingfordevice {
            get {
                return ResourceManager.GetString("Searchingfordevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Item.
        /// </summary>
        public static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Location.
        /// </summary>
        public static string SearchLocation {
            get {
                return ResourceManager.GetString("SearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Change Checklist.
        /// </summary>
        public static string SelectChangeChecklist {
            get {
                return ResourceManager.GetString("SelectChangeChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Change Menu.
        /// </summary>
        public static string SelectChangeMenu {
            get {
                return ResourceManager.GetString("SelectChangeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Checklist.
        /// </summary>
        public static string SelectChecklist {
            get {
                return ResourceManager.GetString("SelectChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Checklist.
        /// </summary>
        public static string SelectedChecklistLabel {
            get {
                return ResourceManager.GetString("SelectedChecklistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Menu.
        /// </summary>
        public static string SelectedMenuLabel {
            get {
                return ResourceManager.GetString("SelectedMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Menu.
        /// </summary>
        public static string SelectMenu {
            get {
                return ResourceManager.GetString("SelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Question.
        /// </summary>
        public static string SelectQuestion {
            get {
                return ResourceManager.GetString("SelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Address or Domain Name.
        /// </summary>
        public static string ServerIPAddressorDomainName {
            get {
                return ResourceManager.GetString("ServerIPAddressorDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        public static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings updated successfully..
        /// </summary>
        public static string ServerSettingsupdatedsuccessfully {
            get {
                return ResourceManager.GetString("ServerSettingsupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site and Settings updated successfully..
        /// </summary>
        public static string SiteandSettingsupdatedsuccessfully {
            get {
                return ResourceManager.GetString("SiteandSettingsupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Time.
        /// </summary>
        public static string SleepTime {
            get {
                return ResourceManager.GetString("SleepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a numeric value..
        /// </summary>
        public static string Specifyanumericvalue {
            get {
                return ResourceManager.GetString("Specifyanumericvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid answer..
        /// </summary>
        public static string Specifyavalidanswer {
            get {
                return ResourceManager.GetString("Specifyavalidanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid temperature value..
        /// </summary>
        public static string Specifyavalidtemperaturevalue {
            get {
                return ResourceManager.GetString("Specifyavalidtemperaturevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Corrective Action..
        /// </summary>
        public static string SpecifyCorrectiveAction {
            get {
                return ResourceManager.GetString("SpecifyCorrectiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Temperature..
        /// </summary>
        public static string SpecifyTemperature {
            get {
                return ResourceManager.GetString("SpecifyTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name/ID.
        /// </summary>
        public static string StoreNameID {
            get {
                return ResourceManager.GetString("StoreNameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Records.
        /// </summary>
        public static string TemperatureRecords {
            get {
                return ResourceManager.GetString("TemperatureRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Review.
        /// </summary>
        public static string TemperatureReview {
            get {
                return ResourceManager.GetString("TemperatureReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatures.
        /// </summary>
        public static string Temperatures {
            get {
                return ResourceManager.GetString("Temperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Server Connection and Web Service.
        /// </summary>
        public static string TestServerConnectionandWebService {
            get {
                return ResourceManager.GetString("TestServerConnectionandWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application and Device ID will be reset..
        /// </summary>
        public static string TheapplicationandDeviceIDwillbereset {
            get {
                return ResourceManager.GetString("TheapplicationandDeviceIDwillbereset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checklist has been added successfully..
        /// </summary>
        public static string Thechecklisthasbeenaddedsuccessfully {
            get {
                return ResourceManager.GetString("Thechecklisthasbeenaddedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkmarks have been cleared successfully..
        /// </summary>
        public static string Thecheckmarkshavebeenclearedsuccessfully {
            get {
                return ResourceManager.GetString("Thecheckmarkshavebeenclearedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkmarks of all the Checklists will be cleared..
        /// </summary>
        public static string ThecheckmarksofalltheChecklistswillbecleared {
            get {
                return ResourceManager.GetString("ThecheckmarksofalltheChecklistswillbecleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkmarks of all the Temperatures and Checklists will be cleared..
        /// </summary>
        public static string ThecheckmarksofalltheTemperaturesandChecklistswillbecleared {
            get {
                return ResourceManager.GetString("ThecheckmarksofalltheTemperaturesandChecklistswillbecleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkmarks of all the Temperatures will be cleared..
        /// </summary>
        public static string ThecheckmarksofalltheTemperatureswillbecleared {
            get {
                return ResourceManager.GetString("ThecheckmarksofalltheTemperatureswillbecleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection with the server and the web service has been established successfully..
        /// </summary>
        public static string Theconnectionwiththeserverandthewebservicehasbeenestablishedsuccessfully {
            get {
                return ResourceManager.GetString("Theconnectionwiththeserverandthewebservicehasbeenestablishedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HACCP Manager application has been temporarily disabled on this device. Please contact the application administrator..
        /// </summary>
        public static string TheHACCPManagerapplicationhasbeentemporarilydisabledonthisdevicePleasecontacttheapplicationadministrator {
            get {
                return ResourceManager.GetString("TheHACCPManagerapplicationhasbeentemporarilydisabledonthisdevicePleasecontactthea" +
                        "pplicationadministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The menu has been updated successfully..
        /// </summary>
        public static string Themenuhasbeenupdatedsuccessfully {
            get {
                return ResourceManager.GetString("Themenuhasbeenupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermometer Mode.
        /// </summary>
        public static string ThermometerMode {
            get {
                return ResourceManager.GetString("ThermometerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout! No Blue2 devices detected. Please try again later..
        /// </summary>
        public static string TimeoutNoBlue2devicesdetectedPleasetryagainlater {
            get {
                return ResourceManager.GetString("TimeoutNoBlue2devicesdetectedPleasetryagainlater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No. of Records.
        /// </summary>
        public static string TotalNoofRecords {
            get {
                return ResourceManager.GetString("TotalNoofRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn ON Bluetooth on your device..
        /// </summary>
        public static string TurnONBluetoothonyourdevice {
            get {
                return ResourceManager.GetString("TurnONBluetoothonyourdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server. Please verify connection settings and try again..
        /// </summary>
        public static string UnabletoconnecttotheserverPleaseverifyconnectionsettingsandtryagain {
            get {
                return ResourceManager.GetString("UnabletoconnecttotheserverPleaseverifyconnectionsettingsandtryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the web service. Please verify connection settings and try again..
        /// </summary>
        public static string UnabletofindthewebservicePleaseverifyconnectionsettingsandtryagain {
            get {
                return ResourceManager.GetString("UnabletofindthewebservicePleaseverifyconnectionsettingsandtryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated the Blue2 settings successfully..
        /// </summary>
        public static string UpdatedtheBlue2settingssuccessfully {
            get {
                return ResourceManager.GetString("UpdatedtheBlue2settingssuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Site and Settings.
        /// </summary>
        public static string UpdateSiteandSettings {
            get {
                return ResourceManager.GetString("UpdateSiteandSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User List.
        /// </summary>
        public static string UpdateUserList {
            get {
                return ResourceManager.GetString("UpdateUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded all the checklist records to HACCP Enterprise application successfully, but unable to upload temperature records..
        /// </summary>
        public static string UploadedallthechecklistrecordstoHACCPEnterpriseapplicationsuccessfullybutunabletouploadtemperaturerecords {
            get {
                return ResourceManager.GetString("UploadedallthechecklistrecordstoHACCPEnterpriseapplicationsuccessfullybutunableto" +
                        "uploadtemperaturerecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded all the records to HACCP Enterprise application successfully..
        /// </summary>
        public static string UploadedalltherecordstoHACCPEnterpriseapplicationsuccessfully {
            get {
                return ResourceManager.GetString("UploadedalltherecordstoHACCPEnterpriseapplicationsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded all the temperature records to HACCP Enterprise  application successfully, but unable to upload checklist records..
        /// </summary>
        public static string UploadedallthetemperaturerecordstoHACCPEnterpriseapplicationsuccessfullybutunabletouploadchecklistrecords {
            get {
                return ResourceManager.GetString("UploadedallthetemperaturerecordstoHACCPEnterpriseapplicationsuccessfullybutunable" +
                        "touploadchecklistrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data from your current server to a different server may result in error and/or corrupt records..
        /// </summary>
        public static string Uploadingdatafromyourcurrentservertoadifferentservermayresultinerrorandorcorruptrecords {
            get {
                return ResourceManager.GetString("Uploadingdatafromyourcurrentservertoadifferentservermayresultinerrorandorcorruptr" +
                        "ecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Records.
        /// </summary>
        public static string UploadRecords {
            get {
                return ResourceManager.GetString("UploadRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update Site Settings as records are pending to be uploaded. To upload the records, select “Upload Records” menu..
        /// </summary>
        public static string UploadRecordsPendingOnUpdateSiteSettingsMessage {
            get {
                return ResourceManager.GetString("UploadRecordsPendingOnUpdateSiteSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update Users as records are pending to be uploaded. To upload the records, select “Upload Records” menu..
        /// </summary>
        public static string UploadRecordsPendingOnUpdateUsersMessage {
            get {
                return ResourceManager.GetString("UploadRecordsPendingOnUpdateUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List updated successfully..
        /// </summary>
        public static string UserListupdatedsuccessfully {
            get {
                return ResourceManager.GetString("UserListupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Status.
        /// </summary>
        public static string ViewStatus {
            get {
                return ResourceManager.GetString("ViewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Uploading data from your current server to a different server may result in errors and/or corrupt records..
        /// </summary>
        public static string WarningUploadingdatafromyourcurrentservertoadifferentservermayresultinerrorsandorcorruptrecords {
            get {
                return ResourceManager.GetString("WarningUploadingdatafromyourcurrentservertoadifferentservermayresultinerrorsandor" +
                        "corruptrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless Tasks.
        /// </summary>
        public static string WirelessTasks {
            get {
                return ResourceManager.GetString("WirelessTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to enter the temperature manually. Please contact the Application Administrator..
        /// </summary>
        public static string YoudonothavepermissiontoenterthetemperaturemanuallyPleasecontacttheApplicationAdministrator {
            get {
                return ResourceManager.GetString("YoudonothavepermissiontoenterthetemperaturemanuallyPleasecontacttheApplicationAdm" +
                        "inistrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You require an active Internet connection to perform some functions. We recommend that you enable Wi-Fi for this purpose. Data charges may apply if Wi-Fi is not enabled..
        /// </summary>
        public static string YourequireanactiveInternetconnectiontoperformsomefunctionsWerecommendthatyouenableWiFiforthispurposeDatachargesmayapplyifWiFiisnotenabled {
            get {
                return ResourceManager.GetString("YourequireanactiveInternetconnectiontoperformsomefunctionsWerecommendthatyouenabl" +
                        "eWiFiforthispurposeDatachargesmayapplyifWiFiisnotenabled", resourceCulture);
            }
        }
    }
}
